print("hello Anuka")
print("   /\      ")
print("  /  \     ")
print(" /    \    ")
print("/______\   ")
print(" _________ ")
print("|         |")
print("|         |")
print("|         |")
print("|_________|")
print("     /\    ")
print("    /  \   ")
print("   /    \  ")
print("  /______\ ")
print(" |\      /|")
print(" | \    / |")
print(" |  \  /  |")
print(" |   \/   |")
print(" |   /\   |")
print(" |  /  \  |")
print(" | /    \ |")
print(" |/______\|")